### ISSUE TITLE
Support emojis

### ISSUE THREAD

**Issue by a-kenji** [friedow/centerpiece#103]
Support emoji's.

![image](https://github.com/friedow/centerpiece/assets/65275785/397d0e1e-b643-4eff-b2e6-744bd98cb76b)

**Comment by friedow** [comment]
The problem here is that our current iced version (0.10) does not support font-fallback. This has recently been merged in iced ([PR](https://github.com/iced-rs/iced/pull/1697)) and is probably fixed once we update to iced 0.12 ([Draft PR](https://github.com/friedow/centerpiece/pull/81)).
