### ISSUE TITLE
CPU: make status show diagrams instead of raw text

### ISSUE THREAD

**Issue by RTUnreal** [friedow/centerpiece#104]
I have too many cpus to show all in the same centerpiece window:
![image](https://github.com/friedow/centerpiece/assets/22859658/54fd0884-7c09-4cf0-ad8a-febbd5a9256f)
KDE Plasma has a bar chart as a status view:
![image](https://github.com/friedow/centerpiece/assets/22859658/143e1451-cacd-4178-9fb8-2646207951fb)

**Comment by friedow** [comment]
Maybe there are some nice symbols in nerdfonts which we can use to display each core in one line. Any suggestions?

**Comment by RTUnreal** [comment]
If you want to stay with only text displays, I would recommend a Windows-style layout in text form so more cores/threads can fit in the small space.

Here are some examples:
![grafik](https://github.com/friedow/centerpiece/assets/22859658/5fe5e9b5-589b-47c2-ae58-9c9c048ff020)
![grafik](https://github.com/friedow/centerpiece/assets/22859658/3ac5a98d-57e2-4b82-bece-d96fa9e4c836)

**Comment by VTimofeenko** [comment]
>Maybe there are some nice symbols in nerdfonts which we can use to display each core in one line. Any suggestions?

I think I have seen glyph \uf4bc,  ` `, used for this purpose

**Comment by friedow** [comment]
I've just created a PR which should fix both #104 and #114. I've used [ascii block elements](https://en.wikipedia.org/wiki/Block_Elements) to visualize per-core usage :). I've left a screenshot of this in the PR.
