### ISSUE TITLE
desktop entries aren't quite rendered correctly

### ISSUE THREAD

**Issue by colemickens** [friedow/centerpiece#110]
I'm attaching some manual `desktop` files I've added to my system to influence app launchers.

Sirula does the right thing here, and shows me only these entries:
- "DetSys" with the regular firefox icon
- "Firefox Nightly Default" with the nightly firefox icon
- (other firefox entries are suppressed by the addition in firefox.desktop)

![screenshot-1711650263](https://github.com/friedow/centerpiece/assets/327028/7f043e6f-8645-4be1-b314-382bf44b337f)
![screenshot-1711650258](https://github.com/friedow/centerpiece/assets/327028/f26d0435-8ae4-4eb6-b93e-8bcf53a47820)

But centerpiece does not:

![screenshot-1711650318](https://github.com/friedow/centerpiece/assets/327028/67efb2a1-f712-43cc-a2a7-e7ae3d22202d)

Related desktop files:

[firefox.desktop.txt](https://github.com/friedow/centerpiece/files/14793939/firefox.desktop.txt)
[firefox-nightly.desktop.txt](https://github.com/friedow/centerpiece/files/14793940/firefox-nightly.desktop.txt)
[firefox-nightly-default.desktop.txt](https://github.com/friedow/centerpiece/files/14793941/firefox-nightly-default.desktop.txt)

**Comment by friedow** [comment]
That one is on me 😅. While implementing the desktop entry search I decided to go the very simple route of just finding all desktop files and displaying their title. But as your example shows, the .desktop specification has a lot more options then just the title ;).

Anyways, I'm tagging this as a bug of course.
