### ISSUE TITLE
CPU: running with 16 cores opens the list at the bottom

### ISSUE THREAD

**Issue by VTimofeenko** [friedow/centerpiece#114]
This is probably applicable to machines with number of cores more than the list height. In my case `grep -c proc /proc/cpuinfo` is 16.

# Steps to reproduce

1. Run `nix run github:friedow/centerpiece`
2. Type "cpu"
3. Use up keyboard arrow to navigate higher in the list

# Expected result

1. The list follows the selection caret and scrolls upwards
2. The list of CPUs opens from the beginning

# Actual result

![image](https://github.com/friedow/centerpiece/assets/9886026/fca23fc0-41f5-4f15-9388-659d93d06ade)

1. The list stays at the very bottom. On this screenshot the selection caret is above the displayed CPUs.

2. The list of CPUs starts at the end

**Comment by friedow** [comment]
Thanks for reporting this bug :). I think  the list of cpu cores being that long is a problem in itself. I'd like to tackle this in https://github.com/friedow/centerpiece/issues/104.
