### ISSUE TITLE
CJK charaters are being rendered as squares

### ISSUE THREAD

**Issue by Guanran928** [friedow/centerpiece#128]
I'm using `Source Han Sans VF` as CJK font, does this mean centerpiece don't support font fallback?
![image](https://github.com/friedow/centerpiece/assets/68757440/1799d6a3-4abc-40dc-9878-8176dc0eb7f9)

**Comment by friedow** [comment]
I've enabled font fallback in #131. Feel free to test that branch and leave a review whether this works for you :).

**Comment by friedow** [comment]
That's weird. I've ran the same command:
```
> nix run github:friedow/centerpiece/pull/131/head -- --version
centerpiece 1.0.0 - 2024-04-15 - 7318ea3
```

The title of this website: https://www.archchinese.com/ is displayed correctly in the brave history plugin:
![image](https://github.com/friedow/centerpiece/assets/17351844/898ebb58-a6e4-4a72-8e15-6bb6e2aa8199)

**Comment by friedow** [comment]
Oh perfect, I'm really happy to hear that :). Will merge the Bugfix branch then!
