### ISSUE TITLE
Load burst due to index-git-repositories service

### ISSUE THREAD

**Issue by mweinelt** [friedow/centerpiece#189]
This service is super I/O heavy and drives the load up to the point where using it isn't fun anymore.

I'd recommend updating the systemd unit to make the service less bursty.

```
        Nice = 19;
        IOSchedulingClass = "best-effort";
        IOSchedulingPriority = 7;
```

**Comment by a-kenji** [comment]
Thank you for the report! I think that is a very reasonable suggestion.

I myself also adjust the time the service itself gets triggered:

```
services.index-git-repositories = {
  enable = true;
  interval = "1h";
};
```
