### ISSUE TITLE
Keystrokes are registered multiple times 

### ISSUE THREAD

**Issue by friedow** [friedow/centerpiece#212]
I've noticed that when typing the same character two times in the searchbox, the character gets registered 3 - 4 times. This results in wrong search results. This happens since we switched to iced_layershell which was merged in https://github.com/friedow/centerpiece/pull/204.

56697f1c36397c24b4378e71eb357cf2f020c088 is fine.
2c87b015d20ffa1405f3728e476dfcc886e5f0bf is broken.

Steps to reproduce:
1. Open up centerpiece
2. Type `successfully` relatively fast
3. Notice how the characters C, S and L appear 3-4 times

**Comment by friedow** [comment]
@Decodetalkers was something like this reported already for iced_layershell?

**Comment by Decodetalkers** [comment]
Emm. no..  can you provide me a video to describe it? Emm maybe because the way I handle the word repeat?

https://github.com/waycrate/exwlshelleventloop/blob/master/layershellev/src/lib.rs#L1201-L1236

logic is here.. I think it should be the same with winit.. maybe there still be something wrong

**Comment by Decodetalkers** [comment]
ok, maybe because that I forgot to add repeat_token..
